name: Update Exchange Rates

on:
  schedule:
    - cron: '18 18 * * *' # Runs daily at midnight IST
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
      KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install --upgrade kaggle

    - name: Run scraper
      run: python daily-currency-update.py

    - name: Create dataset metadata
      run: |
        mkdir -p dataset
        echo '{
          "title": "Daily Updated Exchange Rates (2015-now) (USD)",
          "id": "mathoholic/daily-updated-exchange-rates-2015-now-usd",
          "licenses": [{"name": "CC0-1.0"}],
          "subtitle": "Track daily exchange rates for USD against major global currencies since 2015",
          "description": "Explore a rich collection of daily records capturing the top 56 global currencies from 2015 to the present day. 
                          This meticulously maintained dataset provides valuable insights into currency trends, 
                          exchange rates, and market dynamics.Analyze and research comprehensive data for in-depth currency analysis,
                          enabling you to make informed decisions in a rapidly evolving global financial landscape",
          "resources": [
            {
              "path": "exchange-rates.csv",
              "description": "This dataset provides a comprehensive collection of daily currency exchange rates from 2015 to the present day.
              The file is in CSV format, structured with columns representing the date and exchange rates for various global currencies. 
              Each row represents a specific date, and the corresponding values in the columns denote the exchange rate of each currency relative to an unspecified reference currency. 
              With this dataset, researchers and data enthusiasts can explore and analyze historical currency trends, conduct in-depth market analysis, 
              and gain valuable insights into the dynamics of different currency exchange rates over time.",
            }
          ]
        }' > dataset/dataset-metadata.json

        cp exchange-rates.csv dataset/

    - name: Commit and push if changed
      run: |
        git config --global user.name "Mathoholic"
        git config --global user.email "litemathoholic@gmail.com"
        git add "exchange-rates.csv" "dataset-metadata.json"
        git commit -m "Update exchange rates data" || exit 0
        git push

    - name: Upload to Kaggle
      run: kaggle datasets version -p dataset -m "Updated exchange rates data"
