name: Update Exchange Rates

on:
  schedule:
    - cron: '18 18 * * *' # Runs daily at midnight IST
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install --upgrade kaggle

    - name: Run scraper
      run: python daily-currency-update.py

    - name: Commit and push if changed
      run: |
        git config --global user.name "Mathoholic"
        git config --global user.email "litemathoholic@gmail.com"
        git status
        git add "exchange-rates.csv"
        git commit -m "Update exchange rates data" || exit 0
        git push

    - name: Configure Kaggle
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"${{ secrets.KAGGLE_USERNAME }}\",\"key\":\"${{ secrets.KAGGLE_KEY }}\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Upload to Kaggle
      run: |
        kaggle datasets version \
          --dir-mode zip \
          --message "Updated exchange rates data" \
          --path . \
          --quiet \
          ${{ secrets.KAGGLE_DATASET }}