name: Update Exchange Rates

on:
  schedule:
    - cron: '18 18 * * *' # Runs daily at midnight IST
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pandas tqdm beautifulsoup4 lxml

    - name: Run scraper
      run: python exchange_rate_scraper.py

    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add exchange-rates.csv
        git commit -m "Update exchange rates data" || exit 0
        git push

    - name: Upload to Kaggle
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        kaggle datasets version -p . -m "Updated exchange rates data"